#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
sketchybar --reload

# -------------------------------------------------------------------------------------------------------
# TILING SETTINGS
# -------------------------------------------------------------------------------------------------------
yabai -m config layout                      bsp

yabai -m config top_padding                 0
yabai -m config bottom_padding              0
yabai -m config left_padding                5
yabai -m config right_padding               5
yabai -m config window_gap                  5

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off 

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config insert_feedback_color       0x00010101
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config external_bar 		            all:10:40

# -------------------------------------------------------------------------------------------------------
# RULES
# -------------------------------------------------------------------------------------------------------
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
# yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
# yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
# yabai -m rule --add app="^Zalo$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^SpaceLauncher$" manage=off
yabai -m rule --add app="^LastPass$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Todoist$" manage=off
yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="^Prismatik$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Five9$" manage=off
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Structured$" sticky=on layer=above manage=off

# Debug mode on
yabai -m config debug_output on

echo "yabai configuration loaded.."
