#!/bin/bash
# Atuin Aliases - Generated on Sun Sep 14 10:56:34 +07 2025
# Use 'atuin dotfiles alias set <name> <command>' to restore
# You can also execute this file directly: ./aliases.sh

atuin dotfiles alias set 'ab' 'akio run dbt build -s'
atuin dotfiles alias set 'ad' 'akio run dbt'
atuin dotfiles alias set 'adb' 'astro dev bash --scheduler'
atuin dotfiles alias set 'ado' 'astro dev object import -s airflow_settings.yaml'
atuin dotfiles alias set 'af' 'akio run sqlfluff fix'
atuin dotfiles alias set 'av' 'ansible-vault'
atuin dotfiles alias set 'c' 'echo -ne 033c'
atuin dotfiles alias set 'cc' 'claude'
atuin dotfiles alias set 'cdeg' 'cd /Volumes/exs/git'
atuin dotfiles alias set 'd' 'docker'
atuin dotfiles alias set 'dc' 'docker-compose'
atuin dotfiles alias set 'esh' '/Users/vanducng/.virtualenvs/global/bin/ec2-ssh'
atuin dotfiles alias set 'esm' '/Users/vanducng/.virtualenvs/global/bin/ec2-session'
atuin dotfiles alias set 'etn' '/Users/vanducng/.virtualenvs/global/bin/ec2-tunnel'
atuin dotfiles alias set 'g' 'git'
atuin dotfiles alias set 'g0' 'arc-cli s 1 && arc-cli new-tab https://github.com/careernowbrands/cnb-ds-dbt-order-form'
atuin dotfiles alias set 'g3' 'arc-cli s 1 && arc-cli new-tab https://github.com/careernowbrands/cnb-ds-astro'
atuin dotfiles alias set 'gP' 'git push'
atuin dotfiles alias set 'gc' 'git checkout'
atuin dotfiles alias set 'gcb' 'git checkout -b'
atuin dotfiles alias set 'gd' 'git diff'
atuin dotfiles alias set 'ghas' 'gh auth switch'
atuin dotfiles alias set 'gp' 'git pull'
atuin dotfiles alias set 'gr' 'go run .'
atuin dotfiles alias set 'gs' 'git status'
atuin dotfiles alias set 'gwm' 'git-worktree-manager'
atuin dotfiles alias set 'k' 'kubectl'
atuin dotfiles alias set 'kap' 'kubectl apply -f'
atuin dotfiles alias set 'kdd' 'kubectl describe deployment'
atuin dotfiles alias set 'kdel' 'kubectl delete'
atuin dotfiles alias set 'kdp' 'kubectl describe pod'
atuin dotfiles alias set 'kds' 'kubectl describe service'
atuin dotfiles alias set 'kex' 'kubectl exec -it'
atuin dotfiles alias set 'kga' 'kubectl get all'
atuin dotfiles alias set 'kgd' 'kubectl get deployments'
atuin dotfiles alias set 'kgn' 'kubectl get nodes'
atuin dotfiles alias set 'kgp' 'kubectl get pods'
atuin dotfiles alias set 'kgs' 'kubectl get services'
atuin dotfiles alias set 'klf' 'kubectl logs -f'
atuin dotfiles alias set 'lg' 'lazygit'
atuin dotfiles alias set 'll' 'exa -l'
atuin dotfiles alias set 'ls' 'exa'
atuin dotfiles alias set 'lzd' 'lazydocker'
atuin dotfiles alias set 'nsql' 'nvim +SQLua'
atuin dotfiles alias set 'p' 'python'
atuin dotfiles alias set 'pca' 'pre-commit run --all-files'
atuin dotfiles alias set 'pr' 'poetry run'
atuin dotfiles alias set 'snowsql' '/Applications/SnowSQL.app/Contents/MacOS/snowsql'
atuin dotfiles alias set 't' 'terraform'
atuin dotfiles alias set 'tm' '$HOME/.local/bin/tmux-sessionizer'
atuin dotfiles alias set 'tt' 'taskwarrior-tui'
atuin dotfiles alias set 'v' 'nvim'
