#!/usr/bin/env sh

options=(
	style=round
	width=2.0
	hidpi=on
	# duskfox palette: bright iris active (vivid), muted bg-highlight inactive
	active_color=0xffd4a4ff
	inactive_color=0x40393552
	background_color=0x00000000
)

borders "${options[@]}"
